list.Set( "GlideWheelModels", "models/tf2enhanced/nuva_wheel.mdl", { angle = Angle( 0, 0, 0 ), scale = Vector( 1, 1, 1 ) } )
list.Set( "GlideWheelModels", "models/tf2enhanced/campervan_wheel.mdl", { angle = Angle( 0, 0, 0 ), scale = Vector( 1, 1, 1 ) } )
list.Set( "GlideWheelModels", "models/tf2enhanced/bugatti_wheel.mdl", { angle = Angle( 0, 0, 0 ), scale = Vector( 1, 1, 1 ) } )
list.Set( "GlideWheelModels", "models/tf2enhanced/laika_wheel.mdl", { angle = Angle( 0, 0, 0 ), scale = Vector( 1, 1, 1 ) } )
list.Set( "GlideWheelModels", "models/tf2enhanced/laika_wheel_alt.mdl", { angle = Angle( 0, 0, 0 ), scale = Vector( 1, 1, 1 ) } )
list.Set( "GlideWheelModels", "models/tf2enhanced/laika_wheel_gold.mdl", { angle = Angle( 0, 0, 0 ), scale = Vector( 1, 1, 1 ) } )
list.Set( "GlideWheelModels", "models/tf2enhanced/steamroller_wheel_front.mdl", { angle = Angle( 0, 0, 0 ), scale = Vector( 1, 1, 1 ) } )
list.Set( "GlideWheelModels", "models/tf2enhanced/steamroller_wheel_back.mdl", { angle = Angle( 0, 0, 0 ), scale = Vector( 1, 1, 1 ) } )
